---
- name: Set up utmbox apps
  hosts: utmbox
  become: true
  become_user: chris
  vars:
    brew_packages:
      - bun
      - cloudflare-wrangler
      - cloudflared
      - eza
      - gcc
      - git
      - jj
      - lsof
      - mailpit
      - nvm
      - ripgrep
      - sqlite
      - sqlite-utils
      - wget

  tasks:
    - name: Install notify-app
      ansible.builtin.copy:
        src: /Users/chris/hacks/notifier/notify-app/tmp/notify-app
        dest: /home/chris/notify-app
        owner: chris
        group: chris
        mode: '0700'
      tags:
      - apps

    - name: Install chz
      ansible.builtin.copy:
        src: /Users/chris/hacks/chz/tmp/chz
        dest: /home/chris/chz
        owner: chris
        group: chris
        mode: '0700'
      tags:
      - apps

    - name: Install tar-new.sh
      ansible.builtin.copy:
        src: /Users/chris/hacks/run-books/tar-new.sh
        dest: /home/chris/tar-new.sh
        owner: chris
        group: chris
        mode: '0700'
      tags:
      - apps
      - neww

    - name: Tap bun homebrew tap
      ansible.builtin.shell:
        cmd: |
          brew tap oven-sh/bun
      args:
        creates: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/oven-sh/homebrew-bun
      tags:
      - apps
    
    - name: Install Homebrew packages
      community.general.homebrew:
        name: "{{ brew_packages }}"
        state: present
      # If you don't use FQCN and have the plugin installed, this can be just `homebrew:`

    - name: Ensure .bashrc sets up homebrew paths
      ansible.builtin.lineinfile:
        path: /home/chris/.bashrc
        line: 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"'
      tags:
      - files

    - name: Make NVM directory
      ansible.builtin.file:
        path: /home/chris/.nvm
        state: directory
        owner: chris
        group: chris
        mode: '0755'
      tags:
      - files

    - name: Ensure .bashrc sets up nvm
      ansible.builtin.blockinfile:
        path: /home/chris/.bashrc
        append_newline: true
        prepend_newline: true
        block: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "/home/linuxbrew/.linuxbrew/opt/nvm/nvm.sh" ] && \. "/home/linuxbrew/.linuxbrew/opt/nvm/nvm.sh"  # This loads nvm
          [ -s "/home/linuxbrew/.linuxbrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/home/linuxbrew/.linuxbrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
      tags:
      - files

    - name: Copy bash_aliases file with owner and permissions
      ansible.builtin.copy:
        src: ./bash_aliases
        dest: /home/chris/.bash_aliases
        owner: chris
        group: chris
        mode: '0600'
      tags:
      - files

    - name: Install node via nvm
      ansible.builtin.shell:
        cmd: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "/home/linuxbrew/.linuxbrew/opt/nvm/nvm.sh" ] && \. "/home/linuxbrew/.linuxbrew/opt/nvm/nvm.sh"  # This loads nvm
          [ -s "/home/linuxbrew/.linuxbrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/home/linuxbrew/.linuxbrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
          nvm install v22.22.0
          nvm alias default v22.22.0
        creates: /home/chris/.nvm/versions/node/v$(node -v | cut -d'v' -f2)
      tags:
      - apps
