---
- name: Set up u-lot development on utmbox
  hosts: utmbox
  become: true
  become_user: chris
  tasks:
    - name: Get line-of-time-api source
      ansible.builtin.shell: git clone https://github.com/csterritt/line-of-time-api.git
      args:
        creates: /home/chris/line-of-time-api
      tags:
      - lot

    - name: Get line-of-time-api git branches
      ansible.builtin.shell: git branch | egrep -i dev | wc -l
      register: dev_branch_count
      args:
        chdir: /home/chris/line-of-time-api

    - name: Debug dev branch count
      debug:
        msg: "Dev branch count: {{ dev_branch_count.stdout }}"

    - name: Switch git branch for line-of-time-api
      ansible.builtin.shell: |
        cd /home/chris/line-of-time-api && git checkout -b dev origin/dev && git pull
      when: dev_branch_count.stdout | int == 0
      tags:
      - lot

    - name: Set up line-of-time-api's .dev.vars.all
      ansible.builtin.shell: |
        cp /home/chris/line-of-time-api/.dev.vars.all.template /home/chris/line-of-time-api/.dev.vars.all
      tags:
      - lot

    - name: Ensure .dev.vars.all has the proper DB id
      ansible.builtin.lineinfile:
        path: /home/chris/line-of-time-api/.dev.vars.all
        regexp: '^CLOUDFLARE_DATABASE_ID='
        line: CLOUDFLARE_DATABASE_ID='607b4c0f-122a-40e0-9053-9693451c3298'
      tags:
      - lot

    - name: Set up line-of-time-api's dependencies
      ansible.builtin.shell: |
        PATH=${PATH}:/home/linuxbrew/.linuxbrew/bin ; cd /home/chris/line-of-time-api && npm install && cd line-of-time-fe && npm install && npm run build
      tags:
      - lot

    - name: Set up line-of-time-api's database
      ansible.builtin.shell: |
        PATH=${PATH}:/home/linuxbrew/.linuxbrew/bin ; cd /home/chris/line-of-time-api && ./build-schema-update.sh
      tags:
      - lot

    - name: Install playwright browser
      ansible.builtin.shell: |
        PATH=${PATH}:/home/linuxbrew/.linuxbrew/bin ; cd /home/chris/line-of-time-api && npx playwright install chromium
      tags:
      - lot

    - name: Copy install-chromium-deps.sh with owner and permissions
      ansible.builtin.copy:
        src: ./install-chromium-deps.sh
        dest: /home/chris/install-chromium-deps.sh
        owner: chris
        group: chris
        mode: '0700'
      tags:
      - files

    - name: Run install-chromium-deps.sh
      ansible.builtin.shell: |
        sudo /home/chris/install-chromium-deps.sh
      tags:
      - lot
