---
- name: Set up new-sprite sprite
  hosts: new-sprite
  become: true
  tasks:
    - name: Upgrade all apt packages
      apt:
        force_apt_get: yes
        upgrade: dist
      become: yes
      tags:
      - apps

    - name: Install lsof
      apt:
        name: lsof
        state: latest
      tags:
      - apps

    - name: Install eza
      apt:
        name: eza
        state: latest
      tags:
      - apps

    - name: Install atuin
      apt:
        name: atuin
        state: latest
      tags:
      - apps

    - name: Install tirith
      ansible.builtin.shell: /.sprite/bin/npm install -g tirith
      tags:
      - apps

    - name: Install mailpit
      ansible.builtin.shell: curl -sL https://raw.githubusercontent.com/axllent/mailpit/develop/install.sh> /tmp/mailpit_install.sh && sudo sh < /tmp/mailpit_install.sh && rm -f /tmp/mailpit_install.sh
      tags:
      - apps

    - name: Install notify-apps
      ansible.builtin.copy:
        src: /Users/chris/hacks/notifier/notify-app/tmp/notify-app
        dest: /home/sprite/notify-app
        owner: sprite
        group: sprite
        mode: '0700'
      tags:
      - apps

    - name: Ensure .zshrc sources our .bash_aliases
      ansible.builtin.lineinfile:
        path: /home/sprite/.zshrc
        line: 'source ~/.bash_aliases'
      tags:
      - files

    - name: Ensure .zshrc sets up atuin
      ansible.builtin.lineinfile:
        path: /home/sprite/.zshrc
        line: 'eval "$(atuin init zsh)"'
      tags:
      - files

    - name: Ensure .zshrc sets up tirith
      ansible.builtin.lineinfile:
        path: /home/sprite/.zshrc
        line: 'eval "$(tirith init --shell zsh)"'
      tags:
      - files
      - new

    - name: Copy bash_aliases file with owner and permissions
      ansible.builtin.copy:
        src: ./bash_aliases
        dest: /home/sprite/.bash_aliases
        owner: sprite
        group: sprite
        mode: '0600'
      tags:
      - files
